### ISSUE TITLE
Oa

### ISSUE THREAD

**Issue by notGabo** [westf4ll/MusicPro_ET#1]
Holaaa, pudiste implementar el coso de transbank? soy d otra sede y creo que tenemos el mismo proyecto para integracion de plataformas sldklskd :( he tenido cualquier atados para implementar lo d transbank y cache que tenias un commit que decia que arreglaba esos problemas. Muxas gracias d antemano!!

**Comment by westf4ll** [comment]
> Holaaa, pudiste implementar el coso de transbank? soy d otra sede y creo que tenemos el mismo proyecto para integracion de plataformas sldklskd :( he tenido cualquier atados para implementar lo d transbank y cache que tenias un commit que decia que arreglaba esos problemas. Muxas gracias d antemano!!

holaa, que error tienes?

**Comment by notGabo** [comment]
no puedo seguir hablando por aqui sin que me cierre el issue aaaa 

![image](https://github.com/westf4ll/MusicPro_ET/assets/101845172/cdddf6df-8b37-45a3-864a-4ef08fbc454c)

Ya mira te comento, cuando hago el post a transbank y esta en modo dev, pasa, con algunos problemas pero pasa. Pero cuando lo dejo en un servidor en modo build, me tira un post y me retorna un error404, asumo que es un tema de sincronia, pero aun no logro dar con un arreglo  lskdlksd ;/  si lo has podido solucionarlo me podrias hacer el favor de hablarme a disc porfis (@nafle)? claro, si es que puedes y quieres nomas slkdlk . muchas gracias de antemano !!!

**Comment by westf4ll** [comment]
> no puedo seguir hablando por aqui sin que me cierre el issue aaaa
> 
> ![image](https://user-images.githubusercontent.com/101845172/253379251-cdddf6df-8b37-45a3-864a-4ef08fbc454c.png)
> 
> Ya mira te comento, cuando hago el post a transbank y esta en modo dev, pasa, con algunos problemas pero pasa. Pero cuando lo dejo en un servidor en modo build, me tira un post y me retorna un error404, asumo que es un tema de sincronia, pero aun no logro dar con un arreglo lskdlksd ;/ si lo has podido solucionarlo me podrias hacer el favor de hablarme a disc porfis (@nafle)? claro, si es que puedes y quieres nomas slkdlk . muchas gracias de antemano !!!

 chale no sabría como solucionar eso la vdd :( mi compañero dice que tampoco cacha el pq te dice eso, lo estás haciendo con django o como?
